from distance_detector_app.urls import distance_detector_urlpatterns
from sensors.urls import sensors_urlpatterns
from amp_phase_detector_app.urls import sensor_config_urlpatterns, amp_phase_measurement_urlpatterns
from ports.urls import ports_urlpatterns

urlpatterns = ports_urlpatterns + sensors_urlpatterns + distance_detector_urlpatterns + sensor_config_urlpatterns + amp_phase_measurement_urlpatterns