# Generated by Django 5.0.6 on 2024-09-07 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweeps_per_frame', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('continuous_sweep_mode', models.BooleanField(default=False)),
                ('double_buffering', models.BooleanField(default=False)),
                ('inter_frame_idle_state', models.CharField(choices=[('DEEP_SLEEP', 'DEEP_SLEEP'), ('SLEEP', 'SLEEP'), ('READY', 'READY')], default='DEEP_SLEEP', max_length=10)),
                ('inter_sweep_idle_state', models.CharField(choices=[('DEEP_SLEEP', 'DEEP_SLEEP'), ('SLEEP', 'SLEEP'), ('READY', 'READY')], default='READY', max_length=10)),
                ('sweep_rate', models.FloatField(blank=True, default=None, null=True)),
                ('frame_rate', models.FloatField(blank=True, default=None, null=True)),
                ('start_point', models.IntegerField(blank=True, default=None, null=True)),
                ('num_points', models.IntegerField(blank=True, default=None, null=True)),
                ('step_length', models.IntegerField(blank=True, default=None, null=True)),
                ('profile', models.CharField(blank=True, choices=[('PROFILE_1', 'PROFILE_1'), ('PROFILE_2', 'PROFILE_2'), ('PROFILE_3', 'PROFILE_3'), ('PROFILE_4', 'PROFILE_4'), ('PROFILE_5', 'PROFILE_5')], default=None, max_length=10, null=True)),
                ('hwass', models.IntegerField(blank=True, default=None, null=True)),
                ('receiver_gain', models.IntegerField(blank=True, default=None, null=True)),
                ('enable_tx', models.BooleanField(blank=True, default=None, null=True)),
                ('enable_loopback', models.BooleanField(blank=True, default=None, null=True)),
                ('phase_enhancement', models.BooleanField(blank=True, default=None, null=True)),
                ('prf', models.CharField(blank=True, choices=[('PRF_19_5_MHZ', 'PRF_19_5_MHZ'), ('PRF_15_6_MHZ', 'PRF_15_6_MHZ'), ('PRF_13_0_MHZ', 'PRF_13_0_MHZ'), ('PRF_8_7_MHZ', 'PRF_8_7_MHZ'), ('PRF_6_5_MHZ', 'PRF_6_5_MHZ'), ('PRF_5_2_MHZ', 'PRF_5_2_MHZ')], default=None, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubsweepConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_points', models.IntegerField(default=160, validators=[django.core.validators.MinValueValidator(1)])),
                ('step_length', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('profile', models.CharField(choices=[('PROFILE_1', 'PROFILE_1'), ('PROFILE_2', 'PROFILE_2'), ('PROFILE_3', 'PROFILE_3'), ('PROFILE_4', 'PROFILE_4'), ('PROFILE_5', 'PROFILE_5')], default='PROFILE_3', max_length=10)),
                ('hwass', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(511)])),
                ('receiver_gain', models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('enable_tx', models.BooleanField(default=True)),
                ('enable_loopback', models.BooleanField(default=False)),
                ('phase_enhancement', models.BooleanField(default=False)),
                ('prf', models.CharField(choices=[('PRF_19_5_MHZ', 'PRF_19_5_MHZ'), ('PRF_15_6_MHZ', 'PRF_15_6_MHZ'), ('PRF_13_0_MHZ', 'PRF_13_0_MHZ'), ('PRF_8_7_MHZ', 'PRF_8_7_MHZ'), ('PRF_6_5_MHZ', 'PRF_6_5_MHZ'), ('PRF_5_2_MHZ', 'PRF_5_2_MHZ')], default='PRF_15_6_MHZ', max_length=12)),
            ],
        ),
    ]
