# Generated by Django 5.0.6 on 2024-09-07 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amp_phase_detector_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorconfig',
            name='hwass',
        ),
        migrations.AddField(
            model_name='sensorconfig',
            name='hwaas',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(511)]),
        ),
    ]
