# Generated by Django 5.0.6 on 2024-09-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amp_phase_detector_app', '0002_remove_sensorconfig_hwass_sensorconfig_hwaas'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorconfig',
            name='name',
            field=models.CharField(default='Generated Name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sensorconfig',
            name='profile',
            field=models.CharField(choices=[('PROFILE_1', 'PROFILE_1'), ('PROFILE_2', 'PROFILE_2'), ('PROFILE_3', 'PROFILE_3'), ('PROFILE_4', 'PROFILE_4'), ('PROFILE_5', 'PROFILE_5')], default='PROFILE_3', max_length=10),
        ),
    ]
