# Generated by Django 5.0.6 on 2024-09-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_m', models.FloatField(default=0.25)),
                ('end_m', models.FloatField(default=3.0)),
                ('max_step_length', models.IntegerField(blank=True, null=True)),
                ('max_profile', models.CharField(choices=[('PROFILE_1', 'PROFILE_1'), ('PROFILE_2', 'PROFILE_2'), ('PROFILE_3', 'PROFILE_3'), ('PROFILE_4', 'PROFILE_4'), ('PROFILE_5', 'PROFILE_5')], default='PROFILE_5', max_length=10)),
                ('close_range_leakage_cancellation', models.BooleanField(default=False)),
                ('signal_quality', models.FloatField(default=15.0)),
                ('threshold_method', models.CharField(choices=[('CFAR', 'CFAR'), ('FIXED_AMPLITUDE', 'Fixed Amplitude'), ('FIXED_STRENGTH', 'Fixed Strength'), ('RECORDED', 'Recorded')], default='CFAR', max_length=20)),
                ('peaksorting_method', models.CharField(choices=[('STRONGEST', 'Strongest'), ('NEAREST', 'Nearest')], default='STRONGEST', max_length=20)),
                ('reflector_shape', models.CharField(choices=[('GENERIC', 'Generic'), ('SPECIFIC', 'Specific')], default='GENERIC', max_length=20)),
                ('num_frames_in_recorded_threshold', models.IntegerField(default=100)),
                ('fixed_threshold_value', models.FloatField(default=1.0)),
                ('fixed_strength_threshold_value', models.FloatField(default=1.0)),
                ('threshold_sensitivity', models.FloatField(default=1.0)),
                ('update_rate', models.FloatField(blank=True, default=50.0, null=True)),
            ],
        ),
    ]
