# Generated by Django 5.0.6 on 2024-07-19 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_rename_is_active_sensor_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='status',
            new_name='is_connected',
        ),
    ]
