# Generated by Django 5.0.6 on 2024-07-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_distancedetectorprofile_delete_distanceprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DistanceDetectorProfile',
            new_name='DistanceProfile',
        ),
    ]
