# Generated by Django 5.0.6 on 2024-07-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0009_rename_close_range_leakage_distanceprofile_close_range_leakage_cancellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distanceprofile',
            name='max_profile',
            field=models.CharField(choices=[('PROFILE_1', 1), ('PROFILE_2', 2), ('PROFILE_3', 3), ('PROFILE_4', 4), ('PROFILE_5', 5)], default='PROFILE_5', max_length=10),
        ),
    ]
