# Generated by Django 5.0.6 on 2024-07-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0010_alter_distanceprofile_max_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distanceprofile',
            name='max_profile',
            field=models.IntegerField(choices=[(1, 'Profile 1'), (2, 'Profile 2'), (3, 'Profile 3'), (4, 'Profile 4'), (5, 'Profile 5')], default=3),
        ),
    ]
