# Generated by Django 5.0.6 on 2024-07-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0011_alter_distanceprofile_max_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distanceprofile',
            name='max_profile',
            field=models.CharField(choices=[('PROFILE_1', 'PROFILE_1'), ('PROFILE_2', 'PROFILE_2'), ('PROFILE_3', 'PROFILE_3'), ('PROFILE_4', 'PROFILE_4'), ('PROFILE_5', 'PROFILE_5')], default='PROFILE_5', max_length=10),
        ),
    ]
