# Generated by Django 5.0.6 on 2024-09-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0012_alter_distanceprofile_max_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='hwid',
            field=models.CharField(max_length=100),
        ),
    ]
